---
grails:
    profile: rest-api
    codegen:
        defaultPackage: bursapp
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
            dbCreate: none
            driverClassName: com.mysql.jdbc.Driver
            username: sa
            password: ''
            url: jdbc:mysql://127.0.0.1:3306/bursapp
    test:
        dataSource:
            dbCreate: none
            driverClassName: com.mysql.jdbc.Driver
            username: sa
            password: ''
            url: jdbc:mysql://localhost:3306/bursapp
    production:
       dataSource:
           dbCreate: none
           driverClassName: com.mysql.jdbc.Driver
           username: sa
           password: ''
           url: jdbc:mysql://localhost:3306/bursapp
